window:
  padding:
    x: 6
    y: 0

font:
  size: 13
  offset:
    x: 1
    y: 6
  normal:
    family: FiraCode Nerd Font
    style: Retina
  bold:
    family: FiraCode Nerd Font
    # style: Bold
  italic:
    family: FiraCode Nerd Font
    # style: Italic
  use_thin_strokes: true

colors:
  primary:
    background: '#161821'
    foreground: '#d2d4de'
  normal:
    black:   '#161821'
    red:     '#e27878'
    green:   '#b4be82'
    yellow:  '#e2a478'
    blue:    '#84a0c6'
    magenta: '#a093c7'
    cyan:    '#89b8c2'
    white:   '#c6c8d1'
  bright:
    black:   '#6b7089'
    red:     '#e98989'
    green:   '#c0ca8e'
    yellow:  '#e9b189'
    blue:    '#91acd1'
    magenta: '#ada0d3'
    cyan:    '#95c4ce'
    white:   '#d2d4de'

scrolling:
  history: 100000
  multiplier: 3

key_bindings:
   - { key: M, mods: Command, action: None }
   - { key: Q, mods: Command, action: None }
   - { key: W, mods: Command, action: None }
   - { key: B,  mods: Alt, chars: "\x1bb" }
   - { key: C,  mods: Alt, chars: "\x1bc" }
   - { key: D,  mods: Alt, chars: "\x1bd" }
   - { key: F,  mods: Alt, chars: "\x1bf" }

