name: matrix
root: ~/dev

windows:
  - neo:
      layout: 0ec4,178x40,0,0{51x40,0,0[51x33,0,0,0,51x6,0,34,16],126x40,52,0[126x33,52,0,4,126x6,52,34{63x6,52,34,17,62x6,116,34,18}]}
      panes:
        - figlet node && node -v | cowsay | lolcat
        - node -v && npm -v
        - figlet neo && node -v | cowsay -f dragon-and-cow | lolcat
        - node -v && npm -v
        - node -v && npm -v
  - morpheus:
      layout: 0ec4,178x40,0,0{51x40,0,0[51x33,0,0,0,51x6,0,34,16],126x40,52,0[126x33,52,0,4,126x6,52,34{63x6,52,34,17,62x6,116,34,18}]}
      panes:
        - figlet node && node -v | cowsay | lolcat
        - node -v && npm -v
        - figlet morpheus && node -v | cowsay -f dragon-and-cow | lolcat
        - node -v && npm -v
        - node -v && npm -v
  - trinity:
      layout: 0ec4,178x40,0,0{51x40,0,0[51x33,0,0,0,51x6,0,34,16],126x40,52,0[126x33,52,0,4,126x6,52,34{63x6,52,34,17,62x6,116,34,18}]}
      panes:
        - figlet node && node -v | cowsay | lolcat
        - node -v && npm -v
        - figlet trinity && node -v | cowsay -f dragon-and-cow | lolcat
        - node -v && npm -v
        - node -v && npm -v
  - cypher:
      layout: 579d,178x40,0,0{51x40,0,0,1,126x40,52,0,8}
      panes:
        - figlet node && node -v | cowsay | lolcat
        - figlet cypher && node -v | cowsay -f dragon-and-cow | lolcat
