name: matrix
root: ~/dev

windows:
  - neo:
      layout: cfaa,178x40,0,0{50x40,0,0[50x32,0,0,0,50x7,0,33,1],127x40,51,0[127x34,51,0,2,127x5,51,35{63x5,51,35,3,63x5,115,35,4}]}
      panes:
        - figlet node && node -v | cowsay | lolcat
        - tty-clock -tcD
        - figlet neo && node -v | cowsay -f dragon-and-cow | lolcat
        - lsd
        - node -v
  - morpheus:
      layout: cfaa,178x40,0,0{50x40,0,0[50x32,0,0,0,50x7,0,33,1],127x40,51,0[127x34,51,0,2,127x5,51,35{63x5,51,35,3,63x5,115,35,4}]}
      panes:
        - figlet node && node -v | cowsay | lolcat
        - node -v
        - figlet morpheus && node -v | cowsay -f dragon-and-cow | lolcat
        - lsd
        - node -v
  - trinity:
      layout: cfaa,178x40,0,0{50x40,0,0[50x32,0,0,0,50x7,0,33,1],127x40,51,0[127x34,51,0,2,127x5,51,35{63x5,51,35,3,63x5,115,35,4}]}
      panes:
        - figlet node && node -v | cowsay | lolcat
        - node -v
        - figlet trinity && node -v | cowsay -f dragon-and-cow | lolcat
        - lsd
        - node -v
  - cypher:
      layout: b441,178x41,0,0,6
      panes:
        - figlet cypher && node -v | cowsay -f dragon-and-cow | lolcat
