name: matrix
root: ~/dev

windows:
  - neo:
      layout: 6fcc,140x35,0,0[140x31,0,0{30x31,0,0,0,109x31,31,0,1},140x3,0,32{70x3,0,32,2,69x3,71,32,3}]
      panes:
        - figlet node && node -v | cowsay | lolcat
        - figlet vim rocks! && node -v | cowsay -f dragon-and-cow | lolcat
        - lsd
        - clear
  - morpheus:
      layout: b441,178x41,0,0,4
      panes:
        - csp && figlet csp && node -v | cowsay -f dragon-and-cow | lolcat
  - trinity:
      layout: b441,178x41,0,0,5
      panes:
        - z local && figlet local && node -v | cowsay -f dragon-and-cow | lolcat
  - cypher:
      layout: b441,178x41,0,0,6
      panes:
        - z local && figlet local && node -v | cowsay -f dragon-and-cow | lolcat
